name: Testing & Production Push

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    # Permissions required to publish packages to GHCR
    permissions:
      contents: read
      packages: write

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: 123
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        # --legacy-peer-deps prevents "dependency conflict" errors common in Nerimity
        run: npm install --legacy-peer-deps

      - name: Run Database Generation
        run: npx prisma generate
        env:
          DATABASE_URL: 'postgresql://postgres:123@postgres:5432/postgres'

      - name: Compile and Test Build
        run: npm run build
        env:
          DATABASE_URL: 'postgresql://postgres:123@postgres:5432/postgres'
          DEV_MODE: true
          REDIS_HOST: redis
          REDIS_PORT: 6379
          JWT_SECRET: 'test-secret'

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Downcase Repository Name
        run: |
          echo "IMAGE_NAME_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Production Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.IMAGE_NAME_LOWER }}:latest
