name: Testing & Production Push

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Permissions required to publish packages to GHCR
    permissions:
      contents: read
      packages: write

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: 123
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm i -g pnpm
          pnpm i

      - name: Run Database Migrations and Generation
        run: |
          pnpm run prisma:migrate_dev
          pnpm run prisma:generate
        env:
          DATABASE_URL: 'postgresql://postgres:123@postgres:5432/postgres'
          DATABASE_DIRECT_URL: 'postgresql://postgres:123@postgres:5432/postgres'

      - name: Compile and Test Build
        run: pnpm build
        env:
          DATABASE_URL: 'postgresql://postgres:123@postgres:5432/postgres'
          DATABASE_DIRECT_URL: 'postgresql://postgres:123@postgres:5432/postgres'
          DEV_MODE: true
          REDIS_HOST: redis
          REDIS_PORT: 6379
          JWT_SECRET: 'change me'
          PORT: 80
          MAX_CHANNELS_PER_SERVER: 100
          MAX_INVITES_PER_SERVER: 10
          MAX_ROLES_PER_SERVER: 50

      # =========================================================
      # NEW: Authenticate and Publish Built Image to GHCR
      # =========================================================
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Production Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
